services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        /* Отладка в лог файле */
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
    volumes:
      - plugins_data:/var/www/html/wp-content/plugins
      - ./log/debug.log:/var/www/html/wp-content/debug.log
      - ./source:/var/www/html/wp-content/plugins/in-employee-reports
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  plugins_data: